### ISSUE TITLE
Why is MapML inline in HTML important?

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/MapML#210]
I haven't seen the arguments made for MapML inline in HTML. It would be nice to discuss pros and cons, and why it is important.

I think inline MapML increases the overall complexity of MapML:
1. Browser implementation complexity? Maybe @zcorpan can help answer this.
2. Polyfill code complexity/size
3. Specification complexity:
   - [Tag omission for both text/html and text/mapml](https://github.com/Maps4HTML/MapML/issues/208) as opposed to only text/mapml
   - [Conditional contexts in which elements can be used](https://github.com/Maps4HTML/MapML/issues/74)
   - Probably other things

I think 2. and 3. aren't great arguments against MapML inline in HTML, but perhaps worth taking into consideration.

**Comment by prushforth** [comment]
I think inline mapml is important because I think security considerations will preclude getting events and DOM access to remote mapml content, tbd.  And a DOM API is essential, as this the foundation of programmability.  I think the need for inline MapML is or should be covered by requirements relating to [Client-Side Mapping APIs](https://maps4html.org/HTML-Map-Element-UseCases-Requirements/#client-apis)
