### ISSUE TITLE
What is the MIME type of MapML

### ISSUE THREAD

**Issue by joanma747** [Maps4HTML/MapML#31]
I have found that in this example https://github.com/w3c/sdw/issues/1058 you are using "text/mapml" but I do not see this mentioned in the specification https://maps4html.github.io/MapML/spec.

This is not my only problem: I was writing a OpenAPI document of a service (actually and API) that will return a MapML and I should provide a MIME type and an schema!!.

**Comment by prushforth** [comment]
There are RelaxNG and schematron files that validate MapML to the current spec (I believe) in the schema subdirectory of this repo

**Comment by prushforth** [comment]
Although I haven't registered the media type yet, as we haven't got agreement between W3C and OGC on this format, I expect to register it as "text/mapml".  The registration process is demanding though, especially since we will need to consider security implications of the format, which if implemented in a browser could be non-trivial.  Not that they will be a show stopper, IMHO, but it needs to be taken seriously.  The first step I believe is getting MapML into the WICG incubation process, somehow.  We're still working on that.  In the meantime, I don't think it will hurt to use "text/mapml" in Accept: and Content-Type: headers.

**Comment by Malvoz** [comment]
Closing in favor of https://github.com/Maps4HTML/MapML/issues/139.
