### ISSUE TITLE
Remove mentions of deprecated input types

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/MapML#76]
https://maps4html.org/MapML/spec/#the-input-element:
> There must be at least four input element children of the extent element, including only one of each of the following `type` inputs: `xmin`, `ymin`,`xmax` and `ymax`.

According to the "Changes since the previous draft" section, these (and `projection`) have all been deprecated, so this text should be removed.

I suppose this means there is no requirement of minimum amount of input elements now?

Also probably want to remove (or at least comment out in HTML) the strikethrough text in this table: https://maps4html.org/MapML/spec/#attr-input-type-keywords.

**Comment by prushforth** [comment]
> According to the "Changes since the previous draft" section, these (and projection) have all been deprecated, so this text should be removed.

OK i'll fix that.  Probably time to start working on the spec again, now.  Please raise any other issues you find or don't understand.

> I suppose this means there is no requirement of minimum amount of input elements now?

There's not really a minimum, per se.  The idea behind the `<extent> `is to provide an affordance for the `layer`, sort of binding it to the `map `element's rendered rectangle.  As the map moves, the `extent `drives content retrieval for the `layer `by generating requested events and providing the requested serialized part of the event to link templates which perform content retrieval appropriate to their `link@rel=` value.

The only input that we have still got as mandatory is zoom, but I think we may be able to knock that back to at-the-services-need (SHOULD), with some discussion:

Map services need to know what scale of content to provide, with some exceptions (exceptions which don't represent good practice imho).  In the case of WMS, the scale of rendering is determined by knowing the `width` and `height` of the image to be generated, in addition to the projected bounding box.  In tile services, zoom is a proxy for scale, because for each zoom level, the resolution is a defined quantity, as are the size of the tiles.

From the [spec](https://maps4html.org/MapML/spec/#scale): 

> In the case where a MapML document contains an `extent` element, an `input@type=zoom` MUST be present which controls how the zoom is transmitted from client to server. 

In the case of  WMS services, the only reason I have got zoom listed as `MUST` is because I thought it necessary in order to constrain the zoom range within which the extent would generate requests.  Currently the polyfill will genenrate errors if you don't include the zoom input, but it could coded to be guided by the entire TCRS zoom range in that case instead.  So a zoom input could be treated as a `SHOULD` in IETF terms, so that the client doesn't send the server requests outside the zoom range that the server supports. 

However, the issue remains that the zoom input variable isn't required at all by WMS services, but even so you would have to bind it into the link template that points to the WMS, in order to associate the zoom range to the template that you intend.

> Also probably want to remove (or at least comment out in HTML) the strikethrough text in this table: https://maps4html.org/MapML/spec/#attr-input-type-keywords.

Yes, I'll fix that, too.

Thanks for your note!

**Comment by Malvoz** [comment]
This line has a mention of `extent@action`:
https://github.com/Maps4HTML/MapML/blob/ec2a4ca58baf48fdedcf0b5d92421237eb11431a/spec/index.html#L1280
