### ISSUE TITLE
What is `legendLinks`?

### ISSUE THREAD

**Issue by zcorpan** [Maps4HTML/MapML#80]
```
    readonly attribute LegendLink[] legendLinks;
```

What is this?

**Comment by Malvoz** [comment]
I think the concept of "legend links" is problematic because:

1. It isn't apparent that the link is a destination for legend information (link name derived from the layer name, in the layer control).
2. It requires the user to navigate away from the current document to recieve the information (which in the example in https://github.com/Maps4HTML/MapML/issues/80#issuecomment-653642243 is an [image](http://wms.ess-ws.nrcan.gc.ca/wms/toporama_en?SERVICE=WMS&REQUEST=GetLegendGraphic&LAYER=WMS-Toporama&VERSION=1.1&FORMAT=image/png) with the accessible name of "toporama_en (219×551)", which isn't very useful).
3. Hard/impossible(?) to define a relationship between an object on a map and its corresponding description (if the object and the description lived in the same document you could perhaps define the relationship using [`aria-details`](https://www.w3.org/TR/wai-aria/#aria-details) for example, at least in a polyfill/JS library).

Do we have a UCR issue for this use case and/or capability?

**Comment by prushforth** [comment]
> Do we have a UCR issue for this use case and/or capability?

If we don't, we should do.  It was added to support WMS and WMTS legend links capabilities, because originally I held that support for WMS and WMTS were baseline requirements, so I did my best to accommodate their facilities.

That said, maybe the facility could be reimagined with a better and more accessible UI, and possibly a better API even.  Often times a legend is a vital bit of meta-information about the map, and could be super useful for low-vision users etc.

**Comment by Malvoz** [comment]
> > Do we have a UCR issue for this use case and/or capability?
>
> If we don't, we should do.

https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/37#issue-448625450 specifically mentions legends for the use case "[Display custom web content describing map features](https://maps4html.org/HTML-Map-Element-UseCases-Requirements/#use-case-html-annotations)". 👍🏼

**Comment by Malvoz** [comment]
`legendLinks` removed in https://github.com/Maps4HTML/MapML/pull/213.
